### ISSUE TITLE
How to launch mysql docker on Linux?

### ISSUE THREAD

**Issue by hackjutsu** [BitTigerInst/BitTiger-CS504-FAQ#10]
docker-compose.yml
```
runningInformationDatabase:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root

```

run 
```
docker-compose up -d
```
